### 라이브러리 불러오기

In [3]:
import numpy as np #numpy를 np라고 부르겠다

### 1차원 배열(array) 맏들기

In [4]:
#array는 다양한 값을 어레이로 변환
list1=[1,2,3,4,5]
arr=np.array(list1)
arr

array([1, 2, 3, 4, 5])

In [5]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [12]:
#2차원  array 생성
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#3차원배열
arr3=np.array([1,2,3],[4,5,6],)

### 배열의 크기확인

In [13]:
#shape-배열의 크기
#0차원은 점, 선, 면 중 점이다.
#1차원일때 (4,)
#2차원(2,3)
#3차원(3,2,1)
arr2.shape #2행3열과 비슷

(2, 3)

In [14]:
#size-배열 전체요소의 개수파악가능
arr2.size

6

In [15]:
#ndim-배열의 차원을 이야기한다.
arr2.ndim

2

In [16]:
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3.shape)
print(arr3.ndim)
print(arr3.size)


(2, 2, 2)
3
8


In [17]:
list1=[[[1,2],[3,4]],
      [[5,6],[7,8]]]

In [18]:
arr4=np.array(list1)
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
print(arr3.shape)
print(arr3.ndim)
print(arr3.size)

(2, 2, 2)
3
8


### array생성

In [20]:
#특정한 값으로 배열 생성하기
#0.으로 이루어진 배열생성
#기본적으로 실수형으로 만들어진다.>> 0.
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
#정수로 생성
#dtype 속성을 이용해 데이터 타입 지정
np.zeros((3,4), dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
#1로 이루어진 배열(기본적으로 실수로 생성)
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
#1차원으로만 만들어짐 숫자 한개입력
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#0과1말고 다른거로 채우고 싶다


In [27]:
#np.full((행,열),원하는 값) 3으로 할때
np.full((5,6),3)

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [28]:
#실수로변경
np.full((5,6),3,dtype='float')

array([[3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.]])

In [30]:
#1~50이 담긴 리스트 생성
list1=[]

for i in range(1,51):
    list1.append(i)
print(list1, end=' ')

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50] 

In [32]:
np.array(list1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [33]:
#배열의 형태로 범위 지정 해주는 함수(1~50이 담긴 리스트생성 더 간단)
#0부터시작
np.arange(1,51)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

### 랜덤 값 생성하기

In [34]:
#랜덤값으로 이루어진 배열 생성 (1)
#0~1사이 실수값
arr_ran=np.random.rand(2,3)
arr_ran

array([[0.1112171 , 0.93119533, 0.48717893],
       [0.07058463, 0.53780785, 0.58800698]])

In [36]:
#랜덤값으로 이루어진 배열 생성 (2)
#(시작숫자, 마지막수-1)의 사이 랜덤 정수 1개 생성
arr_ran2=np.random.randint(2,10)
arr_ran2

7

In [39]:
#(시작,끝-1) 사이의 랜덤한 정수, 원하는 크기의 배열 생성
arr_ran3=np.random.randint(2,10, size=(2,3))
arr_ran3

array([[8, 6, 7],
       [9, 3, 5]])

In [40]:
#타입 지정하여 배열 생성
arr_type=np.array([1.2,2.3,3.4], dtype='int')
arr_type

array([1, 2, 3])

In [41]:
#다시 돌아오고싶을때-astype()
arr_type.astype('float')

array([1., 2., 3.])

### array연산

In [49]:
#파이썬 리스트 연산
list1=[1,2,3]
list2=[4,5,6]
list1+list2

[1, 2, 3, 4, 5, 6]

In [50]:
list3=[]
for i range(len(list1)):
    list3.append(list1[i]+list2[i])
list3

SyntaxError: invalid syntax (<ipython-input-50-7731f4e84a4b>, line 2)

In [51]:
#파이썬 리스트를 배열로
arr1=np.array(list1)
arr2=np.array(list2)

In [52]:
arr1

array([1, 2, 3])

In [53]:
arr2

array([4, 5, 6])

In [54]:
#numpy.array연산
#array연산은 기본적으로 요소별 연산이 진행됨
arr1+arr2

array([5, 7, 9])

### 배열 인덱싱, 슬라이싱

### 인덱싱

In [55]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
#특정 행 인덱싱
arr[0]

array([1, 2, 3])

In [58]:
#특정행, 특정 열 인덱싱
arr[0][0]

1

In [59]:
arr[0,0]

1

In [63]:
arr[0,2]

3

### 슬라이싱

In [66]:
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [68]:
#1차원 배열 슬라이싱
arr1[3:8]

array([3, 4, 5, 6, 7])

In [69]:
#2차원 배열 슬라이싱
#0~50까지 범위 배열로 만들기
#(5,10)크기로 크기 변환 해주세요
arr1=np.arange(0,51)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [72]:
#reshape()-배열의 크키를 다시 지정
#원래배열의 요소갯수와 바뀔 배열의 요소갯수가 같아야 한다.
arr2=np.arange(1,51).reshape(5,10)
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [73]:
#2차원 배열 슬라이싱
#슬라이싱할 범위지정 ':'
#[ 행의 범위, 열의 범위]
#[:값]-처음부터 값 전까지
#[값:]-값부터 끝까지
#[:]-처음부터 끝까지
arr2[:2,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [74]:
arr2[:,:2]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42]])

In [75]:
arr2[1:4,:5]

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])

In [76]:
arr2[2,1]

22

In [77]:
arr2[2,3]

24

In [78]:
#행값만 지정해서 2,3행만 출력된것
arr2[[2,3]]

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [ ]:
#동시에 두가지가리기고싶을때
#','를 기준으로 행과 열로 나뉜다
#arr2[[행1,행2],[열1,열2]]
arr2[[2,3],[1,2]]

In [81]:
arr2[[3,4],[3,4]]

array([34, 45])

175.2,180.3,175,169.2,185.2,188.0,177.6,178.2,177,179.0
65.6,88.0,79.2,69.3,55.0,71.2,73.0,68.9,74.0,82.0

### BMI구하기

In [95]:
#np.loadtxt(파일명.확장자, 구분문자) 은 numpy파일을 불러오는 함수
#delimter 구분기호
data=np.loadtxt('height_weight.txt',delimiter=',')
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [98]:
#데이터를 키와 무게로 담아주기
height=data[0]
weight=data[1]
print(height)
print(weight)

[175.2 180.3 175.  169.2 185.2 188.  177.6 178.2 177.  179. ]
[65.6 88.  79.2 69.3 55.  71.2 73.  68.9 74.  82. ]


In [105]:
#bmi지수구하기
arr1=np.array(height)
arr2=np.array(weight)
arr3=arr2/arr1/arr1*10000
#bmi=weight/height**2) 제곱!!
print(arr3)

[21.37153104 27.07018468 25.86122449 24.20652885 16.03543423 20.14486193
 23.14392095 21.69720651 23.62028791 25.59220998]


In [1]:
import numpy as np

### Boolean인덱싱

In [2]:
#Boolean : True/False(논리연산자)
#True 값 출력
#False 값은 축력하지않음
#불리언 자료형- 논리자료형이라한다
#참과 거짓

In [3]:
num = np.random.randint(50,101,size=6)
num

array([95, 76, 59, 57, 82, 82])

In [4]:
num>=80

array([ True, False, False, False,  True,  True])

In [5]:
num[ num>=80 ] #인덱싱하여 사용할 수 있다

array([95, 82, 82])

In [7]:
num<=80

array([False,  True,  True,  True, False, False])

In [8]:
num[num<=80]

array([76, 59, 57])

In [9]:
#변수명 [인덱스위치]
#불리언 인댁싱
#변수명[조건]
num[0] #첫번째있는것

95

In [10]:
num[4] #5번째 있는것

82

In [11]:
name=np.array(['세인','운동','점심','누리'])
name

array(['세인', '운동', '점심', '누리'], dtype='<U2')

In [12]:
bol=np.array([True, False, True, False])
bol

array([ True, False,  True, False])

In [14]:
#True에 해당 값만 출력됨
name[bol]

array(['세인', '점심'], dtype='<U2')

In [19]:
#데이터 생성
name_score=np.array([['세연',100],
          ['명훈',80],
          ['동현',30],
          ['경성',50]])
name_score

array([['세연', '100'],
       ['명훈', '80'],
       ['동현', '30'],
       ['경성', '50']], dtype='<U3')

In [20]:
#이름 값만 슬라이싱 해오기
#[행,열]
name_score[:,:1]

array([['세연'],
       ['명훈'],
       ['동현'],
       ['경성']], dtype='<U3')

In [21]:
name_score[:,0]

array(['세연', '명훈', '동현', '경성'], dtype='<U3')

In [22]:
name_score[:,0] == '세연'

array([ True, False, False, False])

In [26]:
#위치를 알기 힘들다>>조건 필터링을 해보자
#name_score[0]-위치에 따라서 인덱싱
name_score[name_score[:,0] == '세연']

array([['세연', '100']], dtype='<U3')

### numpy다양한 함수들
-sum : 합계
-mean : 평균
-abs : 절댓값

In [31]:
#1~10까지가 담긴 1차원 배열 생성 arange()
arr=np.arange(1,11)
#위의 배열을 (2행,5열) 크기로 변환 :reshape()
arr=np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
arr.size

10

In [32]:
#np.sum()--합계
#요소 전체의 합
np.sum(arr)

55

In [33]:
print(np.sum(arr))
print(arr.sum())

55
55


In [48]:
arr.sum(axis=0)

array([ 7,  9, 11, 13, 15])

In [43]:
#축방향=>>axis=0
#열방향=>>axis=1
print(np.sum(arr,axis=1))
np.sum(arr, axis=0)

[15 40]


array([ 7,  9, 11, 13, 15])

In [34]:
#np.mean()--평균
#요소 전체 평균
print(np.mean(arr))
print(arr.mean())

5.5
5.5


In [35]:
#np.abs()-절댓값
arr2=np.array([1,-2,3,-4,5])
arr2

array([ 1, -2,  3, -4,  5])

In [36]:
np.abs(arr2)

array([1, 2, 3, 4, 5])

In [44]:
arr2.abs

AttributeError: 'numpy.ndarray' object has no attribute 'abs'