In [3]:
import pandas as pd
import numpy as np

# Series

## Series 생성

In [4]:
population=pd.Series([9904312,3448737,2890451,246605])
population

0    9904312
1    3448737
2    2890451
3     246605
dtype: int64

In [5]:
#인덱스 지정하여 생성
#pd.Series()
population=pd.Series([9904312,3448737,2890451,246605],
                    index=['서울','부산','인천','대구'])
population


서울    9904312
부산    3448737
인천    2890451
대구     246605
dtype: int64

### Series 데이터확인
-values : 값 확인
-index : 인덱스 확인
-dtype : 데이터 타입 확인

In [6]:
population.values

array([9904312, 3448737, 2890451,  246605], dtype=int64)

In [7]:
population.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [8]:
population.dtype

dtype('int64')

### Series 이름 지정
-name

In [9]:
#series에 이름달기
population.name='인구'
#인덱스에 이름달기
population.index.name='도시'

In [10]:
population

도시
서울    9904312
부산    3448737
인천    2890451
대구     246605
Name: 인구, dtype: int64

### Series 연산

In [11]:
population/1000000

도시
서울    9.904312
부산    3.448737
인천    2.890451
대구    0.246605
Name: 인구, dtype: float64

In [12]:
population

도시
서울    9904312
부산    3448737
인천    2890451
대구     246605
Name: 인구, dtype: int64

### Series 인덱싱, 슬라이싱

In [13]:
#인덱싱
#Series에서는 index에 값을 지정시 인덱스 값으로 인덱싱 가능
#즉, index번호와 index값 둘 다 인덱싱에 사용 가능
print(population[1])
print(population['부산'])
print(population['대구'])
print(population[3])
print(population['인천'])
population[1]

3448737
3448737
246605
246605
2890451


3448737

In [14]:
population

도시
서울    9904312
부산    3448737
인천    2890451
대구     246605
Name: 인구, dtype: int64

In [15]:
population[[0,3,1]]

도시
서울    9904312
대구     246605
부산    3448737
Name: 인구, dtype: int64

In [16]:
#인덱스 값으로 동일하게 인덱싱하기
print(population[['서울','대구','부산']])


도시
서울    9904312
대구     246605
부산    3448737
Name: 인구, dtype: int64


In [17]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [18]:
arr[[0,3,1]]

array([1, 4, 2])

In [19]:
#Boolean인덱싱 1
#조건문(ex;>, <...)
population>=2500000

도시
서울     True
부산     True
인천     True
대구    False
Name: 인구, dtype: bool

In [20]:
population

도시
서울    9904312
부산    3448737
인천    2890451
대구     246605
Name: 인구, dtype: int64

In [21]:
population[population>=2500000]

도시
서울    9904312
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [22]:
#5000000이하의 도시만 인덱싱
population<=5000000

도시
서울    False
부산     True
인천     True
대구     True
Name: 인구, dtype: bool

In [23]:
population[population<=5000000]

도시
부산    3448737
인천    2890451
대구     246605
Name: 인구, dtype: int64

In [24]:
#두가지 이상의 조건으로 boolean 인덱싱
#인구수가 250만 이상, 500만 이하의 도시
#2500000<x<5000000 이런식으로 안됨 나누어서 따로쓰고 괄호로 묵어줘야함
#&와 ||>>>and 와 or 
population[(population>=2500000) & (population<=5000000)] 

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [25]:
#Series 슬라이싱
print(population[0:4])  #[이상, 미만]
print(population['서울':'대구'])  #[이상, 이하] >>> 인덱스 값일때
population[:3]

도시
서울    9904312
부산    3448737
인천    2890451
대구     246605
Name: 인구, dtype: int64
도시
서울    9904312
부산    3448737
인천    2890451
대구     246605
Name: 인구, dtype: int64


도시
서울    9904312
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [26]:
population

도시
서울    9904312
부산    3448737
인천    2890451
대구     246605
Name: 인구, dtype: int64

### 딕셔너리 객체로 Series생성
-딕셔너리KEY, value로 구성되어 있다
-KEY값은 INDEX
-value 값은 value

In [27]:
data={'아구몬' :9631482, '피요몬':3393191,
     '텐토몬':1490158,"가부몬":2632035}
digi=pd.Series(data)
digi

아구몬    9631482
피요몬    3393191
텐토몬    1490158
가부몬    2632035
dtype: int64

In [28]:
data2={'아구몬':9904312,'피요몬':3448737,'텐토몬':2466052,"테일몬":2890451}
digi_levelup=pd.Series(data2)
digi_levelup

아구몬    9904312
피요몬    3448737
텐토몬    2466052
테일몬    2890451
dtype: int64

In [29]:
#레벨업후의 올라간 공격력 계산
#numpy배열로 되어있다. 그래서 연산가능 list는 불가
attack=digi_levelup-digi
attack

가부몬         NaN
아구몬    272830.0
테일몬         NaN
텐토몬    975894.0
피요몬     55546.0
dtype: float64

In [30]:
#notnull()-변수명이다
attack[attack.notnull()]
attack.notnull()

가부몬    False
아구몬     True
테일몬    False
텐토몬     True
피요몬     True
dtype: bool

In [31]:
#true값출력할때(비어있지 않은 데이터 확인)
attack[attack.notnull()]

아구몬    272830.0
텐토몬    975894.0
피요몬     55546.0
dtype: float64

In [32]:
#비어있는 데이터 확인- 결측지 
#변수명.isnull()
attack.isnull()

가부몬     True
아구몬    False
테일몬     True
텐토몬    False
피요몬    False
dtype: bool

In [33]:
attack[attack.isnull()]

가부몬   NaN
테일몬   NaN
dtype: float64

In [34]:
#레벨업해서 올라간 공격력의 증감율
#(레벨업-레벨업전) / 레벨업전 *100
up_down=(digi_levelup-digi)/digi*100
up_down

가부몬          NaN
아구몬     2.832690
테일몬          NaN
텐토몬    65.489297
피요몬     1.636984
dtype: float64

### Sries 데이터 갱신, 추가, 삭제

In [35]:
#시리즈 데이터 갱신
#소수점자리가 안 맞으면 많이 있는길이에 맞춰줌
up_down['아구몬']=2.8
up_down['텐토몬']=65.5
up_down['피요몬']=1.6

In [36]:
up_down['텐토몬']=65.5
up_down['피요몬']=1.6

In [37]:
up_down

가부몬     NaN
아구몬     2.8
테일몬     NaN
텐토몬    65.5
피요몬     1.6
dtype: float64

In [38]:
#시리즈 데이터 삭제     이미삭제했는데 또하니깐 에러뜸/cell에서 run all누르면됨
del up_down['가부몬']
up_down

아구몬     2.8
테일몬     NaN
텐토몬    65.5
피요몬     1.6
dtype: float64

In [39]:
del up_down['테일몬']

In [40]:
#변수명[새로운값]=값 >> >>> >>> 시리즈에 값 추가
#변수명[기존의 인덱스 값]=값 >> 해당 인덱스의 값이 수정
up_down['테일몬']=3.4
up_down

아구몬     2.8
텐토몬    65.5
피요몬     1.6
테일몬     3.4
dtype: float64

In [41]:
up_down.values

array([ 2.8, 65.5,  1.6,  3.4])

### DataFrame

### DataFrame 생성

In [42]:
#딕셔너리 객체로 DataFrame생성
#key : 칼럼 이름

data={'2015':[9904312,3448737,2890451,2466052],
      '2010':[9631482,3393191,2632035,2431774]}

df=pd.DataFrame(data)
df

2015     2010
0  9904312  9631482
1  3448737  3393191
2  2890451  2632035
3  2466052  2431774

In [43]:
#DataFrame 인덱스 수정
df.index=['서울','부산','인천','대구']
df

2015     2010
서울  9904312  9631482
부산  3448737  3393191
인천  2890451  2632035
대구  2466052  2431774

In [44]:
#리스트 객체로 DataFrame생성
#이름과 값이 있는 모든 것을 객체라고 함
data=[[9904312,3448737,2890451,2466052],
     [9631482,3393191,2632035,2431774]]
col=['서울','부산','인천','대구']
ind=['2015','2010']

df2=pd.DataFrame(data,index=ind,columns=col)
df2

서울       부산       인천       대구
2015  9904312  3448737  2890451  2466052
2010  9631482  3393191  2632035  2431774

In [45]:
data=[[9904312,9631482],
    [3448737,3393191],
     [2890451,2632035],
    [2466052,2431774]]
ind=['서울','부산','인천','대구']
col=['2015','2010']
pd.DataFrame(data,index=ind,columns=col)

2015     2010
서울  9904312  9631482
부산  3448737  3393191
인천  2890451  2632035
대구  2466052  2431774

In [46]:
#변수명.T - 행과 열이 바뀐다(=전치)
#견경한것은 아니고 전치된것을 보여 준것이다
#df2=df2.T라고 치면 변경됨
df2.T

2015     2010
서울  9904312  9631482
부산  3448737  3393191
인천  2890451  2632035
대구  2466052  2431774

In [47]:
df2=df2.T  #이렇게 쳐야 진짜 변경됨

### DataFrame 값 확인
-value 값확인
-index 인덱스 확인
-columns 걸럼 확인

In [48]:
df2.values

array([[9904312, 9631482],
       [3448737, 3393191],
       [2890451, 2632035],
       [2466052, 2431774]], dtype=int64)

In [49]:
df2.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [50]:
df2.columns

Index(['2015', '2010'], dtype='object')

### DataFrame 인덱싱, 슬라이싱

In [51]:
df2

2015     2010
서울  9904312  9631482
부산  3448737  3393191
인천  2890451  2632035
대구  2466052  2431774

In [52]:
#컬럼 인덱싱
#결과가 Series로 출력

df2['2015']

서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 2015, dtype: int64

In [53]:
#대괄호 2번쓰면 결과를 DataFramd으로 출력
df2[['2015']]

2015
서울  9904312
부산  3448737
인천  2890451
대구  2466052

In [54]:
#두개 이상의 컬럼명 인덱싱
df2[['2015','2010']]

2015     2010
서울  9904312  9631482
부산  3448737  3393191
인천  2890451  2632035
대구  2466052  2431774

In [55]:
df2[['2010','2015']]

2010     2015
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

In [56]:
#새로운 컬럼 생성
#변수명[컬럼이름]=값
df2['2005']=[9762546,3512547,2517680,2456016]
df2

2015     2010     2005
서울  9904312  9631482  9762546
부산  3448737  3393191  3512547
인천  2890451  2632035  2517680
대구  2466052  2431774  2456016

In [57]:
#df 행 (index)슬라이싱
df2[1:3]

2015     2010     2005
부산  3448737  3393191  3512547
인천  2890451  2632035  2517680

In [67]:
df2

2015     2010     2005
서울  9904312  9631482  9762546
부산  3448737  3393191  3512547
인천  2890451  2632035  2517680
대구  2466052  2431774  2456016

In [68]:
df2.loc[['서울','인천','대구'],:]

2015     2010     2005
서울  9904312  9631482  9762546
인천  2890451  2632035  2517680
대구  2466052  2431774  2456016

In [58]:
#지정된 인덱스 값으로 슬라이싱
df2['부산':'인천']

2015     2010     2005
부산  3448737  3393191  3512547
인천  2890451  2632035  2517680

In [59]:
#행과 열을 한번에 인덱싱/슬라이싱 해주는 함수
#loc[] 인덱서 : index값(문자)을 사용
#iloc[] : index의 번호(정수)를 사용  i는 int정수를 뜻한다.
# [행,열]

In [60]:
df2.loc['부산':'인천','2015':'2010']

2015     2010
부산  3448737  3393191
인천  2890451  2632035

In [61]:
df2.loc[:,['2010']]

2010
서울  9631482
부산  3393191
인천  2632035
대구  2431774

In [62]:
df2.loc[:,'2010']   #[]이걸2번해줘야함

서울    9631482
부산    3393191
인천    2632035
대구    2431774
Name: 2010, dtype: int64

In [63]:
#iloc 인덱서
df2.iloc[3]

2015    2466052
2010    2431774
2005    2456016
Name: 대구, dtype: int64

In [64]:
df2.iloc[1:3,1:3]

2010     2005
부산  3393191  3512547
인천  2632035  2517680

In [65]:
df2.iloc['부산':'인천','2010':'2005'] #iloc는 0,1,2..자릿수를 써줘야함

TypeError: cannot do positional indexing on Index with these indexers [부산] of type str